databases:
  - name: mybackenddb
    plan: free
    databaseName: mybackend
    user: mybackend

services:
  - type: web
    plan: free
    name: mybackend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mybackend.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mybackenddb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
